In [1]:
import numpy as np

In [4]:
numbers= np.random.rand(5)
print(numbers)

[0.36466471 0.65364822 0.82668611 0.95735318 0.28804976]


In [5]:
array=np.random.rand(2,3)
array

array([[0.31193982, 0.13446031, 0.91175111],
       [0.25083636, 0.87465155, 0.76422536]])

In [6]:
array2= np.random.randn(2,3)
array2 # mean 0 and sd 1

array([[ 1.29975905, -1.33676558, -0.0230275 ],
       [-0.16501467, -1.11507419,  1.09437467]])

In [9]:
array3= np.random.randint(1,10,size=3)
array3

array4= np.random.randint(1,100,size=(2,3))
array4

array([[51, 25, 21],
       [27, 49, 59]])